apiVersion: apps/v1
kind: Deployment
metadata:
  name: edutech-deployment
spec:
  selector:
    matchLabels:
      app: edutech-pod
  template:
    metadata:
      labels:
        app: edutech-pod
    spec:
      containers:
      - name: edutech-container
        image: edutechdocker:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
